services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      POSTGRES_HOST: timescaledb
      POSTGRES_DB: minicurso_ev 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
    ports:
      - "5434:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - ev-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: smart-aqua-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: ''
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ev-network
    depends_on:
      - timescaledb
    restart: unless-stopped

  mqtt-explorer:
    image: ghcr.io/thomasnordquist/mqtt-explorer:latest
    container_name: mqtt-explorer
    ports:
      - "4000:3000"
    environment:
      - MQTT_EXPLORER_USERNAME=admin
      - MQTT_EXPLORER_PASSWORD=admin
    volumes:
      - mqtt_explorer_data:/app/data
    networks:
      - ev-network
    restart: unless-stopped

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - .:/workspace:cached # Mapeia a pasta do código para dentro
      - ../curso:/workspace/curso:cached # Mapeia a pasta curso para dentro do workspace
    command: sleep infinity # Mantém o container ligado para o aluno usar
    networks:
      - ev-network
    # Variáveis de ambiente para o container/Codespace
    # Para rodar localmente, use o arquivo .env na raiz do projeto
    environment:
      - AWS_PUBLIC_IP=56.126.34.58
      - MQTT_PORT=1883
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=minicurso_ev
volumes:
  timescale_data:
  grafana_data:
  mqtt_explorer_data:

networks:
  ev-network:
    driver: bridge
